(function(){
const imgs=[
'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=85',
'https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=900&q=85',
'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=900&q=85',
'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=900&q=85',
'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=900&q=85',
'https://images.unsplash.com/photo-1598560917505-59a3ad559071?auto=format&fit=crop&w=900&q=85'
];
const names=['Royal Kundan Choker','Celeste Pearl Drop','Aria Solitaire Ring','Meera Antique Jhumka','Noor Gold Kada','Saanvi Pendant Set','Aadhya Bridal Haar','Ira Rose Gold Hoops','Veda Kundan Ring','Tara Layered Chain','Riya Mangalsutra','Anaya Pearl Choker','Zara Halo Ring','Myra Temple Jhumka','Kiara Gold Bangle','Avni Polki Pendant','Diya Bridal Set','Aarohi Diamond Studs','Navya Kundan Kada','Ishita Chain Pendant','Siya Classic Ring','Rhea Chandbali','Aanya Heritage Bangle','Mahi Mangalsutra','Esha Pearl Drops','Kavya Statement Choker','Naina Solitaire Band','Tia Floral Jhumka','Sara Rose Gold Bangle','Vanya Polki Set','Anvi Minimal Pendant','Isha Bridal Necklace'];
const cats=['Necklace','Earrings','Rings','Bangles','Mangalsutra','Pendants'];
const products=names.map((name,i)=>{const cat=cats[i%cats.length]; const price=1899+((i*733)%7600); const old=Math.round(price*(1.18+((i%4)*.08))); return {id:i+1,name,category:cat,price,oldPrice:old,discount:Math.round((1-price/old)*100),rating:4.4+(i%6)*.1,reviewCount:47+i*13,metal:['Gold','Silver','Rose Gold'][i%3],polish:['High Polish','Antique','Matte'][i%3],stone:['Kundan','Pearl','Lab Solitaire','Polki'][i%4],material:i%3===0?'925 Sterling Silver':'Premium Brass Core',plating:i%3===1?'22K Yellow Gold Plating':'18K Rose Gold Plating',dimensions:'Adjustable / Universal',weight:(12+i%8)+' grams',warranty:'1 Year Complete Warranty',delivery:'Dispatched in 24–48 Hours',stock:3+(i%9),badge:i<4?'BESTSELLER':i<8?'NEW':'SIGNATURE',desc:'Aurelia craftsmanship meets modern Indian elegance in this finely finished piece, designed for celebrations and everyday heirloom moments.',img:imgs[i%imgs.length],images:[imgs[i%imgs.length],imgs[(i+1)%imgs.length],imgs[(i+2)%imgs.length]]};});
const coupons={FIRST10:{type:'percent',value:10,min:0},WELCOME15:{type:'percent',value:15,min:1500},FESTIVE20:{type:'percent',value:20,min:3000},FLAT500:{type:'flat',value:500,min:2999}};
window.AureliaData={products,coupons,categories:cats.map(c=>({name:c})),getProductById:id=>products.find(p=>p.id===Number(id)),search:q=>products.filter(p=>(p.name+' '+p.category+' '+p.metal+' '+p.stone).toLowerCase().includes(String(q).toLowerCase())),getProductsByCategory:c=>products.filter(p=>p.category.toLowerCase()===String(c).toLowerCase()),async syncFromServer(){try{if(window.AureliaAPI){const r=await AureliaAPI.get('/products');if(Array.isArray(r.products)&&r.products.length){this.products.splice(0,this.products.length,...r.products);return r.products}}}catch(e){console.warn('Using cached catalogue:',e.message)}return this.products}};
})();
